### ISSUE TITLE
Allow compression of streams

### ISSUE THREAD

**Issue by lukevp** [deno-libs/compression#3]
This middleware is really handy!  Thanks for providing it.

I think it would be more flexible if it could operate on a stream (or string, or buffer), rather than directly reading in the file. 

The limitation of the current implementation is, if I want to dynamically create a file and send it down to the browser compressed (for example, say I want to read in a template file and create a filled in template as an html string in memory), I don't see a way to do this without first writing it to a file.

**Comment by lukevp** [comment]
I've opened PR #5 to satisfy this request, please let me know what you think, and if there's anything you'd like changed.

**Comment by v1rtl** [comment]
closed via #5
